// Generated by CoffeeScript 1.7.1
var Schema, Track, TrackSchema, mongoose;

mongoose = require('mongoose');

Schema = mongoose.Schema;

TrackSchema = new Schema({
  title: String,
  artist: String,
  addedBy: String,
  addedDate: String,
  url: String,
  src: String,
  order: Number,
  service: String,
  duration: String
});

Track = mongoose.model('Track', TrackSchema);

module.exports = {
  Track: Track,
  Schema: TrackSchema
};
