// Generated by CoffeeScript 1.7.1
var app, certPath, express, fs, https, keyPath, options, server;

fs = require('fs');

https = require('https');

express = require('express');

app = express();

app.set('views', __dirname + '/../views');

app.set('view engine', 'jade');

app.use(express.bodyParser());

app.use(express.methodOverride());

app.use(app.router);

app.use(express["static"]("" + __dirname + "/../public"));

app.use(express.errorHandler({
  showStack: true,
  dumpExceptions: true
}));

keyPath = __dirname + '/../ssl/server.key';

certPath = __dirname + '/../ssl/server.crt';

options = {
  key: fs.readFileSync(keyPath),
  cert: fs.readFileSync(certPath)
};

app.get('/', function(req, res) {
  return res.render('index', {
    title: 'Disko'
  });
});

server = https.createServer(options, app);

server.listen(3000, function() {
  return console.log('https://localhost:' + config.port);
});
