// Generated by CoffeeScript 1.7.1
var Playlist, Track, colors, convertDuration, dispatch, get_source, infos_sc, infos_yt, request, request_url, sources, ytParseDuration;

request = require('request');

colors = require('colors');

Track = require('./models/track').Track;

Playlist = require('./models/playlist').Playlist;

sources = {
  youtube: {
    resolver: "https://www.googleapis.com/youtube/v3/videos?key=",
    content: "&part=snippet,contentDetails&id=",
    key: "AIzaSyCxL2W7WQKGQ_IKN9ug37rxeJm-Hr0t7Fw",
    documentation: "https://developers.google.com/youtube/v3/docs/videos?hl=fr"
  },
  soundcloud: {
    resolver: "https://api.soundcloud.com/resolve.json?consumer_key=",
    content: "&url=",
    key: "b45b1aa10f1ac2941910a7f0d10f8e28",
    documentation: "https://developers.soundcloud.com/docs/api/reference"
  }
};


/* find from which site is the video */

get_source = function(track, callback) {
  var index, res;
  for (index in sources) {
    if (track.indexOf(index) > -1) {
      res = index;
    }
  }
  return callback(res);
};

String.prototype.build_url = function(source) {
  var src;
  src = sources[source];
  return src.resolver + src.key + src.content + this;
};

ytParseDuration = function(time) {
  var hours, iOh, iOm, iOs, minutes, res, seconds;
  res = '';
  time = time.slice(2);
  iOh = time.indexOf('H');
  if (iOh > -1) {
    hours = time.slice(0, iOh);
    time = time.slice(iOh + 1);
  }
  iOm = time.indexOf('M');
  if (iOm > -1) {
    minutes = time.slice(0, iOm);
    time = time.slice(iOm + 1);
  }
  iOs = time.indexOf('S');
  if (iOs > -1) {
    seconds = time.slice(0, iOs);
  }
  if (seconds < 10) {
    seconds = '0' + seconds;
  }
  if (hours > 0 && minutes < 10) {
    minutes = '0' + minutes;
  }
  if (hours > 0 && minutes === void 0) {
    minutes = '00';
  }
  if (!(minutes === 0 || minutes === void 0)) {
    if (!(hours > 0)) {
      return minutes + ':' + seconds;
    } else {
      return hours + ':' + minutes + ':' + seconds;
    }
  } else {
    return '0:' + seconds;
  }
};

convertDuration = function(time) {
  var hours, inSeconds, minutes, seconds;
  inSeconds = Math.floor(time / 1000);
  hours = Math.floor(inSeconds / 3600);
  inSeconds = inSeconds - hours * 3600;
  minutes = Math.floor(inSeconds / 60);
  seconds = inSeconds - minutes * 60;
  if (seconds < 10) {
    seconds = '0' + seconds;
  }
  if (hours > 0 && minutes < 10) {
    minutes = '0' + minutes;
  }
  if (!(minutes === 0 || minutes === void 0)) {
    if (!(hours > 0)) {
      return minutes + ':' + seconds;
    } else {
      return hours + ':' + minutes + ':' + seconds;
    }
  } else {
    return seconds;
  }
};

request_url = function(url, callback) {
  return request(url, function(error, response, html) {
    if (error && (response.statusCode !== 200)) {
      return console.log("Error:" + err);
    } else {
      return callback(response.body);
    }
  });
};

infos_yt = function(content, callback) {
  var track;
  track = new Track({
    title: content.snippet.title,
    artist: content.snippet.channelTitle,
    url: 'http://www.youtube.com/watch?v=' + content.id,
    src: content.id,
    service: 'Youtube',
    duration: ytParseDuration(content.contentDetails.duration)
  });
  return callback(track);
};


/* get the information from the responses and create objects to be stored in our DB */

infos_sc = function(content, callback) {
  var track;
  track = new Track({
    title: content.title,
    artist: content.user.username,
    url: content.permalink_url,
    src: content.id,
    service: 'Soundcloud',
    duration: convertDuration(content.duration)
  });
  return callback(track);
};


/* manages the actions of dispatching between the different sources */

dispatch = function(track, callback) {
  return get_source(track, function(src) {
    var s, stop, url;
    url = null;
    switch (src) {
      case "youtube":
        s = track.split("v=");
        if (s[1]) {
          s = s[1].split("&");
          track = s[0];
        } else {
          stop = true;
        }
        break;
      case "soundcloud":
        break;
      default:
        console.log("SOURCE NOT SUPPORTED YET".red);
        stop = true;
    }
    if (!stop) {
      url = track.build_url(src);
      return request_url(url, function(res) {
        var parsed;
        switch (src) {
          case "youtube":
            parsed = JSON.parse(res);
            if (parsed.pageInfo.totalResults === 0) {
              return callback({
                code: 0
              });
            } else {
              return infos_yt(JSON.parse(res).items[0], callback);
            }
            break;
          case "soundcloud":
            parsed = JSON.parse(res);
            if (parsed.kind === 'track') {
              return infos_sc(JSON.parse(res), callback);
            } else {
              return callback({
                code: 0
              });
            }
        }
      });
    } else {
      return callback({
        code: 0
      });
    }
  });
};

exports.dispatch = dispatch;
