// Generated by CoffeeScript 1.7.1
var Asset, Playlist, Schema, assetSchema, mongoose, playlistSchema;

mongoose = require('mongoose');

Schema = mongoose.Schema;

assetSchema = new Schema({
  title: String,
  author: String,
  addedBy: String,
  addedDate: String,
  url: String,
  src: String
});

playlistSchema = new Schema({
  title: String,
  owner: String,
  editors: [
    {
      id: String
    }
  ],
  visibility: String,
  content: [assetSchema]
});

Playlist = mongoose.model('Playlist', playlistSchema);

Asset = mongoose.model('Asset', assetSchema);

module.exports = {
  getList: function(callback) {},
  get: function(id, callback) {
    PlayList.find({
      _id: id
    }, function(err, data) {
      callback(err, data);
    });
  },
  remove: function(id, callback) {},
  update: function(id, data, callback) {},
  getSongList: function(callback) {},
  addSong: function(idPlayList, song, callback) {},
  removeSong: function(idPlayList, idSong, callback) {}
};
