// Generated by CoffeeScript 1.7.1
var app, express, fs, http, https, mongoose, path, server, stylus;

fs = require('fs');

path = require('path');

https = require('https');

http = require('http');

express = require('express');

mongoose = require('mongoose');

stylus = require('stylus');

app = express();

app.set('views', path.normalize(__dirname + '/views'));

app.set('view engine', 'jade');

app.set('view options', {
  pretty: true
});

app.use(express.bodyParser());

app.use(express.methodOverride());

app.use(express.cookieParser("your secret here"));

app.use(express.session());

app.use(app.router);

app.use(stylus.middleware("" + __dirname + "/../public"));

app.use(express["static"]("" + __dirname + "/../../public"));

app.configure("development", function() {
  return app.use(express.errorHandler({
    dumpExceptions: true,
    showStack: true
  }));
});

app.configure("production", function() {
  return app.use(express.errorHandler());
});

mongoose.connect('mongodb://localhost/disko_dev');

require('./controllers/routes')(app);

server = http.createServer(app);

server.listen(3000, function() {
  return console.log('http://localhost:3000');
});
