// Generated by CoffeeScript 1.7.1
var app, express, fs, http, https, mongoose, path, server;

fs = require('fs');

path = require('path');

https = require('https');

http = require('http');

express = require('express');

mongoose = require('mongoose');

app = express();

app.set('views', path.normalize(__dirname + '/views'));

app.set('view engine', 'jade');

app.set('view options', {
  pretty: true
});

app.use(express.bodyParser());

app.use(express.methodOverride());

app.use(express.cookieParser("your secret here"));

app.use(express.session());

app.use(app.router);

app.configure("development", function() {
  return app.use(express.errorHandler({
    dumpExceptions: true,
    showStack: true
  }));
});

app.configure("production", function() {
  return app.use(express.errorHandler());
});

<<<<<<< HEAD:lib/server.js
mongoose.connect('mongodb://localhost/disko_dev');
=======
Account = require("../models/account").Account;

passport.use(new LocalStrategy(Account.authenticate()));

passport.serializeUser(Account.serializeUser());

passport.deserializeUser(Account.deserializeUser());

mongoose.connect("mongodb://localhost/passport_local_mongoose");
>>>>>>> 8e72183384650a63c426ebd4d546bdc31a209b02:lib/controllers/server.js

require('./controllers/routes')(app);

server = http.createServer(app);

server.listen(3000, function() {
  return console.log('http://localhost:3000');
});
