// Generated by CoffeeScript 1.7.1
var Track, colors, dispatch, get_source, infos_sc, infos_yt, mongoose, request, request_url, sources;

request = require('request');

colors = require('colors');

mongoose = require('mongoose');

Track = require('../models/track').Track;

sources = {
  youtube: {
    resolver: "https://www.googleapis.com/youtube/v3/videos?key=",
    content: "&part=snippet&id=",
    key: "AIzaSyCxL2W7WQKGQ_IKN9ug37rxeJm-Hr0t7Fw",
    documentation: "https://developers.google.com/youtube/v3/docs/videos?hl=fr"
  },
  soundcloud: {
    resolver: "https://api.soundcloud.com/resolve.json?consumer_key=",
    content: "&url=",
    key: "b45b1aa10f1ac2941910a7f0d10f8e28",
    documentation: "https://developers.soundcloud.com/docs/api/reference"
  }
};


/* find from which site is the video */

get_source = function(track, callback) {
  var index, res;
  for (index in sources) {
    if (track.indexOf(index) > -1) {
      res = index;
    }
  }
  return callback(res);
};

String.prototype.build_url = function(source) {
  var src;
  src = sources[source];
  return src.resolver + src.key + src.content + this;
};

request_url = function(url, callback) {
  return request(url, function(error, response, html) {
    if (error && (response.statusCode !== 200)) {
      return console.log("Error:" + err);
    } else {
      return callback(response.body);
    }
  });
};


/* get the information from the responses and create objects to be stored in our DB */

infos_sc = function(content, callback) {
  var track;
  track = new Track({
    title: content.title,
    author: content.user.username,
    url: content.uri,
    src: "soundcloud",
    id: content.id
  });
  return callback(track);
};

infos_yt = function(content, callback) {
  var track;
  track = new Track({
    title: content.snippet.title,
    author: content.snippet.channelTitle,
    url: "http://www.youtube.com/watch?v=" + content.id,
    src: "youtube",
    id: content.id
  });
  return callback(track);
};


/* manages the actions of dispatching between the different sources */

dispatch = function(track, callback) {
  return get_source(track, function(src) {
    var s, stop, url;
    url = null;
    switch (src) {
      case "youtube":
        s = track.split("v=");
        if (s[1]) {
          s = s[1].split("&");
          track = s[0];
        } else {
          stop = true;
        }
        break;
      case "soundcloud":
        break;
      default:
        console.log("SOURCE NOT SUPPORTED YET".red);
        stop = true;
    }
    if (!stop) {
      url = track.build_url(src);
      return request_url(url, function(res) {
        var parsed;
        switch (src) {
          case "youtube":
            parsed = JSON.parse(res);
            if (parsed.pageInfo.totalResults === 0) {
              return callback({
                code: 0
              });
            } else {
              return infos_yt(JSON.parse(res).items[0], callback);
            }
            break;
          case "soundcloud":
            console.log(url.red);
            parsed = JSON.parse(res);
            if (parsed.kind === 'track') {
              return infos_sc(JSON.parse(res), callback);
            } else {
              return callback({
                code: 0
              });
            }
        }
      });
    } else {
      return callback({
        code: 0
      });
    }
  });
};

exports.dispatch = dispatch;
