// Generated by CoffeeScript 1.7.1
var Playlist, passport;

passport = require('passport');

Playlist = require('../models/playlist').Playlist;

module.exports = function(app) {
  app.get('/', function(req, res) {
    console.log('GET index');
    return res.render('index', {
      title: 'Disko'
    });
  });
  app.get('/playlist/:id.json', function(req, res) {
    console.log('GET playlist' + req.params.id + ' JSON object');
    return Playlist.find({
      id: req.params.id
    }, function(err, data) {
      if (!err) {
        return res.json({
          result: 'OK',
          content: data
        });
      } else {
        return res.json({
          result: 'error',
          content: null
        });
      }
    });
  });
  app.get('/playlists.json', function(req, res) {
    console.log('GET playlist' + req.params.id + ' JSON object');
    return Playlist.find({}, function(err, data) {
      if (!err) {
        return res.json({
          result: 'OK',
          content: data
        });
      } else {
        return res.json({
          result: 'error',
          content: null
        });
      }
    });
  });
  return app.get('/ping', function(req, res) {
    return res.send('pong!', 200);
  });
};
