// Generated by CoffeeScript 1.7.1
var Account, passport;

passport = require('passport');

Account = require('./models/account'.Account);

module.exports = function(app) {};

app.get('/', function(req, res) {
  return res.render('index', {
    title: 'Disko',
    user: req.user
  });
});

app.get('/register', function(req, res) {
  return res.render('register', {
    title: 'Disko'
  }, {});
});

app.post('/register', function(req, res) {
  return Account.register(new Account({
    username: req.body.username
  }), req.body.password, function(err, account) {
    if (err) {
      res.render('register', {
        info: "Sorry. That username already exists. Try again."
      });
    }
    return passport.authenticate('local', function(req, res) {
      return res.redirect('/');
    });
  });
});

app.get('/login', function(req, res) {
  return res.render('login', {
    title: 'Disko',
    user: req.user
  });
});

app.post('/login', passport.authenticate('local', function(req, res) {
  return res.redirect('/');
}));

app.get('/logout', function(req, res) {
  req.logout();
  return res.redirect('/');
});

app.get('/ping', function(req, res) {
  return res.send('pong!', 200);
});
