// Generated by CoffeeScript 1.7.1
var app, express, fs, http, https, server;

fs = require('fs');

https = require('https');

http = require('http');

express = require('express');

app = express();

app.set('views', __dirname + '/../views');

app.set('view engine', 'jade');

app.use(express.bodyParser());

app.use(express.methodOverride());

app.use(app.router);

app.use(express["static"]("" + __dirname + "/../../public"));

app.use(express.errorHandler({
  showStack: true,
  dumpExceptions: true
}));

require('./routes')(app);

server = http.createServer(app);

server.listen(3000, function() {
  return console.log('http://localhost:3000');
});
