// Generated by CoffeeScript 1.7.1
var Account, LocalStrategy, app, express, fs, http, https, passport, server;

fs = require('fs');

https = require('https');

http = require('http');

express = require('express');

passport = require('passport');

LocalStrategy = require('passport-local').Strategy;

app = express();

app.set('views', __dirname + '/../views');

app.set('view engine', 'jade');

app.set("view options", {
  layout: false
});

app.use(express.bodyParser());

app.use(express.methodOverride());

app.use(express.cookieParser("your secret here"));

app.use(express.session());

app.use(passport.initialize());

app.use(passport.session());

app.use(app.router);

app.use(express["static"]("" + __dirname + "/../../public"));

app.configure("development", function() {
  return app.use(express.errorHandler({
    dumpExceptions: true,
    showStack: true
  }));
});

app.configure("production", function() {
  return app.use(express.errorHandler());
});

Account = require("../models/account");

passport.use(new LocalStrategy(Account.authenticate()));

passport.serializeUser(Account.serializeUser());

passport.deserializeUser(Account.deserializeUser());

mongoose.connect("mongodb://localhost/passport_local_mongoose");

require('./routes')(app);

server = http.createServer(app);

server.listen(3000, function() {
  return console.log('http://localhost:3000');
});
